version: "3"
services:
  nginx:
    build:
      context: nginx
    ports:
      - "8080:80"

  web:
    image: node:10.16
    volumes:
      - ./web/kakurankun:/var/kakurankun
    working_dir: "/var/kakurankun"
    command: bash -c "npm install && npm run dev"
    environment:
      - "HOST=0.0.0.0"
    expose:
      - "3000"
